### ISSUE TITLE
Documentation is slightly outdated?

### ISSUE THREAD

**Issue by skatkov** [pay-rails/pay#140]
There seems to be a mismatch between documentation and actual functionality. Initial `bin/rails pay:install:migrations` command created 4 migrations, but documentation suggests that it should be 3.

Adding extra 'AddFieldsToBillable.rb' to the list of new migrations.

Content of this migration is really interesting, it creates additional columns for billable table and how to change it. 

Seems like documentation is slightly outdated. But it's a really important part of documentation as it seems.

**Comment by excid3** [comment]
Good catch! We just added a new migration for v2.1 that came out last week. 👍

**Comment by archonic** [comment]
I just installed myself and found migration issues. It's more than a documentation issue though.

1. It looks like the first migration, `add_fields_to_billable.pay.rb` can be removed since it's overwritten by `add_pay_billable_to_users`. Seem right?
2. The migration `add_pay_billable_to_users` is named wrong as it defines `AddPayToUsers`.

I can write a PR for this if you like.

**Comment by pablogravielseo** [comment]
Same issue here.
