### ISSUE TITLE
Billable for User, payments on other models?

### ISSUE THREAD

**Issue by macfanatic** [pay-rails/pay#175]
We're using the subscription functionality for organizations with success, but building out a more traditional store type flow for customers in our project.

It's unclear to me if I could make use of some of the functionality for this, ie:

```ruby
class Customer
  include Pay::Billable
end

class Invoice
  has_one :payment, class_name: 'Pay::Charge', ....
end
```

Everything I've looked through in the billable module seems like charges are tied super closely together with the model itself.  Additionally, I'll be taking payments on Stripe connect and sending additional params for that platform application fee.

If you feel like this is part of the library's strengths, I'd like to hear it. I'm leaning towards just implementing the connect integration for the customer along with the payments (perhaps using hosted invoices even) outside of pay entirely.

Thanks for any input @excid3!

**Comment by excid3** [comment]
We haven't really gotten into any actual marketplace support with Pay yet, but that's one of the goals I have for the project.

A billable object is just anyone who is paying (a Stripe customer) so that could be the business (your customer) and the businesses customer (their customer). In a marketplace, you'd have both as Billable.

Charges are tied to the Billable objects, just like they are in Stripe. You can charge the businesses to use your service, and you can charge the businesses customers to buy from that business.

The only piece we haven't implemented quite yet is the extra argument to charge the businesses' customers on behalf of the businesses Stripe account. That is where you add your application fee.

It shouldn't be too bad to add that, we just need to add the extra parameters there. Possibly it makes sense to introduce a new method like `marketplace_charge` that requires those other arguments and handles everything separately from the normal `charge` method.

**Comment by macfanatic** [comment]
Thanks for the feedback, I'll investigate a bit more deeply on our requirements to see if there are other potential issues with the integration outside just fee capture.
