### ISSUE TITLE
Prevent network issues using idempotent requests ?

### ISSUE THREAD

**Issue by drewscott** [pay-rails/pay#188]
This could help duplicated subscriptions and charges in the event of network issues. 

https://stripe.com/docs/api/idempotent_requests

**Comment by excid3** [comment]
Yep! Since you need to pass in the same key each time, it probably needs to be done outside of Pay and passed in when you make a charge or subscription.

This gets sent in the second hash of options in the Stripe Ruby methods if someone wants to make a PR to pull out this option in the `charge` and `subscribe` args.

```ruby
charge = Stripe::Charge.create({
  amount: 2000,
  currency: "usd",
  source: "tok_visa", # obtained with Stripe.js
  description: "My First Test Charge (created for API docs)"
}, {
  idempotency_key: "MLiPkjS2LabYa98k"
})
```

**Comment by drewscott** [comment]
Added pull request #191

**Comment by excid3** [comment]
This is now done using the built-in idempotency key support from the Stripe gem.

d7c9291
