### ISSUE TITLE
User should be subscribed after cancelling but before current period runs out

### ISSUE THREAD

**Issue by grk** [pay-rails/pay#206]
I'm looking at the following case:

1. User is subscribed, the current period ends at 2020-11-04.
2. `user.subscribed?` returns `true`
3. I run `user.subscription.cancel`
4. Subscription status is set to `canceled`, ends_at is set to `Wed, 04 Nov 2020 00:00:00 UTC +00:00`
5. `user.subscribed?` returns `false`

Is this intended behavior? Is there another method to check if a user has an active or canceled-but-still-valid subscription?

After a look at the code, I think
```ruby
    def active?
      ["trialing", "active"].include?(status) && (ends_at.nil? || on_grace_period? || on_trial?)
    end
```
could be changed to
```ruby
    def active?
      ["trialing", "active", "canceled"].include?(status) && (ends_at.nil? || on_grace_period? || on_trial?)
    end
```
to solve this issue, but I'm not sure what's the intention here.

**Comment by excid3** [comment]
It's always more complicated that it seems.

First, there are two types of cancellations. The normal "cancel" is a "cancel at period end" so the subscription is still considered active. A "cancel_now!" is going to cancel immediately rendering the user's subscription no longer active.

If I remember correctly, if you update a Stripe subscription to cancel at period end, it will still be marked as active (since it is until the end of the period). This is why we don't immediately mark the subscription as canceled since it can be resumed. 

The `canceled` state is now more intended for permanently canceled subscriptions that cannot resume. The webhooks will update this state once it's officially canceled.

Braintree is a little different, but similar. I forget the details on it but I believe we also leave them as `active` but set the `ends_at` to mark the end of period.

**Comment by grk** [comment]
It looks like it varies between providers.

For stripe, it only updates ends_at: https://github.com/pay-rails/pay/blob/master/lib/pay/stripe/subscription.rb#L14

For braintree, it also sets status to canceled https://github.com/pay-rails/pay/blob/master/lib/pay/braintree/subscription.rb#L18

The paddle integration that is now in PR mirrors the braintree implementation: https://github.com/pay-rails/pay/pull/165/files#diff-70e5b9b87d118453409bd24de79b0d1eR14

This feels a bit confusing, and I think might be better if would be consistent?

**Comment by excid3** [comment]
Since there are no webhooks from Braintree (iirc) on final cancellation, I am marking it as canceled immediately to try to keep it consistent with Stripe. We could leave it as "active" forever, but that didn't seem great.

This is the rabbit hole of trying to keep ever-changing APIs semi-consistent. 😅
