### ISSUE TITLE
Trial subscription with SCA

### ISSUE THREAD

**Issue by rob-rhs** [pay-rails/pay#230]
From the initial class method it looks like Pay::Payment is intended to handle setup_intents, but it delegates :amount which is not a setup_intent attribute. This causes an error in the payments/show view when trying to create a subscription with a free trial using a card requiring SCA. Am I missing something in how i'm implementing?

**Comment by excid3** [comment]
Actually, it's used for PaymentIntents, not SetupIntents. PaymentIntents do have an amount since they're for a specific charge. 👍

For a subscription with a free trial, you would:

1. Create a SetupIntent and render the checkout form
2. Trigger SCA in the Javascript when you collect the card
3. Submit the form
4. Attach payment method to the user
5. Create the subscription with trial

Without a trial, creating the subscription could require action and Pay would raise a Pay::ActionRequired error and give you a Pay::Payment to handle SCA for the PaymentIntent that was generated by the subscription.

**Comment by rob-rhs** [comment]
That's interesting, I thought you were handling a setup intent created by stripe when you create a subscription with a trial. 
I hadn't realised you could proactively create a setup intent and use that to create a payment method before creating a subscription, maybe Stripe documentation has changed or i just missed it! That also explains why you have a confirmCardSetup in your Stripe Elements JS, which was also confusing me.
Thanks, will have a look again with a new perspective!

**Comment by excid3** [comment]
It's just easier if you do it ahead of time. The Stripe subscription will create a pending setup intent if you hadn't, but this flow saves a submit to the server and redirect to fill out the setup intent. 👍 

Here are some docs to check out on all this: https://stripe.com/docs/billing/migration/strong-customer-authentication#scenario-2

**Comment by rob-rhs** [comment]
Tried it today - a much slicker workflow. Thanks for the quick response, Chris.

**Comment by excid3** [comment]
You're welcome!
