### ISSUE TITLE
Configure which emails we want to send or not

### ISSUE THREAD

**Issue by suan** [pay-rails/pay#234]
Thanks for the awesome library!

Would be great if we could configure which emails we want to send or not, eg in my case I don't want to send a renewal email but still want all the others.

**Comment by excid3** [comment]
I agree. That would be nice. 👍 

Not sure if the configuration would be several booleans or an array of emails. 

For now, if you wanted to disable them, you could override the mailer methods to do nothing.

**Comment by stevepolitodesign** [comment]
We'll probably want to wait until #393 is merged until we address this, but I figured I'd outline some thoughts.

**What model should be responsible for handling this?**

Should this be a responsibility of the `Pay::Subscription` or the `Owner`? Or, do we create a new model like `Pay::MailerSubscription`? 

I'm envisioning the`Pay::MailerSubscription` having an `owner_id`, `mailer`, `action`, and `subscribed` columns similar [to this](https://github.com/stevepolitodesign/rails-new-auto-unsubscribe-from-email-in-rails/blob/unsubscribe_link/app/models/mailer_subscription.rb#L14-L17).

The `mailer` would just be the name of the Mailer Class ("pay_user_mailer" in this case) and the `action` would just be the name of the available Mailer actions (receipt, refund, subscription_renewing, and  payment_action_required)

We could set the default value of `subscribed` to `true` so that it's an opt-out strategy. Then we could add a method on the `Owner` [similar to this](https://github.com/stevepolitodesign/rails-new-auto-unsubscribe-from-email-in-rails/blob/unsubscribe_link/app/models/user.rb#L9) that determines if they're subscribe to a Mailer or not.

That would allow us to do something like this:

```ruby
# lib/pay/stripe/webhooks/subscription_renewing.rb
...
return unless subscription && subscription.customer.owner.subscribed_to_mailer?  
```

**Comment by stevepolitodesign** [comment]
@excid3 yeah that's a lot simpler. I can make  PR and start exploring this.

**Comment by excid3** [comment]
It's all yours 👍
