### ISSUE TITLE
method_missing': undefined method json_column?

### ISSUE THREAD

**Issue by katakeynii** [pay-rails/pay#255]
Hi 
After installing pay-rails (using 2.4 version) I have this error : `method_missing': undefined method `json_column?'
![image](https://user-images.githubusercontent.com/6898114/104493863-95835180-55cd-11eb-87b0-23d87deea1d3.png)
Does anyone faced this once ? Do I miss something ?
Current work around for me actually is overriding app/models/pay/charge.rb 
![image](https://user-images.githubusercontent.com/6898114/104494163-00cd2380-55ce-11eb-8502-91fd658c6621.png)

**Comment by excid3** [comment]
Can you share any more details? Is it failing on boot or when you're doing something else?

I installed it on a brand new Rails app and was able to access `Pay::Charge.first` without running into this.

**Comment by dberardo** [comment]
@katakeynii i have also come across this issue. I think this is due to the fact that you are using rails < 6.

the error comes from the subscription model: https://github.com/pay-rails/pay/blob/master/app/models/pay/subscription.rb

i suggest you to patch it, simply create a pay/subscription.rb file in your models/ folder, copy the content of the file above and comment the json_columns? method.

I have managed to setup the Pay environment and on top of the patch of the above model, i also had to do add the following stub to one of the migrations generated by the library:

```ruby
# This migration comes from pay (originally 20200603134434)
class AddDataToPayModels < ActiveRecord::Migration[4.2]
  def change
    add_column :pay_subscriptions, :data, data_column_type
    add_column :pay_charges, :data, data_column_type
  end

  def data_column_type
    if Rails::VERSION::MAJOR >= 6
      default_hash = ActiveRecord::Base.configurations.default_hash
      # Rails 6.1 uses a symbol key instead of a string
    else
      default_hash = ActiveRecord::Base.configurations["default"]
    end
    adapter = default_hash.dig(:adapter) || default_hash.dig("adapter")
    

    case adapter
    when "mysql2"
      :json
    when "postgresql"
      :jsonb
    else
      :text
    end
  end
end
```

this is due to the fact the Rails database configuration structure changes in Rails 6 since multiple DB hosts are allowed.

I am a new user of this library, so i cannot tell you if those patches will result into bugs in other modules.

**Comment by dberardo** [comment]
@excid3 it would be nice if you make the library backward compatible to Rails < 6

**Comment by excid3** [comment]
We're just going to support Rails 6.0+ for Pay v3.
