### ISSUE TITLE
Migration "add_pay_billable_to_users" ERROR: column "pay_data" of relation "users" already exists 

### ISSUE THREAD

**Issue by k2director** [pay-rails/pay#402]
Hi, I'm following the GoRails Stripe Checkout video from April 21 but couldn't get past the migrations for the Pay gem. 
Pay 2.7.2 and Stripe 5.38 both bundled fine, and then I did the migration steps: 

bin/rails pay:install:migrations
bin/rails g pay:billable User
and bin/rails db:migrate

All of the migrations worked, except the last one (add_pay_billable_to_users ). It aborted, saying "ERROR: column "pay_data" of relation "users" already exists"...

But looking at my Schema, my users table DOES NOT have a :Pay_data column. 

Here is the migration that's failing, when it gets to the "t.public_send(Pay::Adapter.json_column_type, :pay_data)" line...

class AddPayBillableToUsers < ActiveRecord::Migration[6.1]
  def change
    change_table :users, bulk: true do |t|
      t.string :processor
      t.string :processor_id
      t.public_send(Pay::Adapter.json_column_type, :pay_data)
      t.datetime :trial_ends_at
      t.string :card_type
      t.string :card_last4
      t.string :card_exp_month
      t.string :card_exp_year
      t.text :extra_billing_info
    end
  end
end

I notice that a previous migration (add_data_to_pay_billable.pay.rb), which successfully migrated, also deals with the :pay_data column in this line: 
    Pay.billable_models.each do |model|
      add_column model.table_name, :pay_data, Pay::Adapter.json_column_type
    end

Any guidance appreciated, thanks!

**Comment by excid3** [comment]
We tried to use `Pay.billable_models` to load the models that include the `Pay::Billable` model in them to magically add that column for you. Unfortunately, with lazying loading it doesn't work reliably.

You can remove the `add_data_to_pay_billable.pay.rb` migration and just stick with the AddPayBillableToUsers so it doesn't generate duplicate columns.

Pay v3 which is coming out soon is going to fix all this and replace it with a Pay::Customer table instead of having to add columns to User.

**Comment by k2director** [comment]
Thanks for the quick response, Chris (as usual)! I rolled back the migration, and all is working now. Very excited to delve into Pay (with Stripe), thanks for sharing it with the community!
