### ISSUE TITLE
Support for setting a default payment processor

### ISSUE THREAD

**Issue by cjavilla-stripe** [pay-rails/pay#518]
Right now, I'm only using one payment processor. Rather than needing to call `set_payment_processor(:stripe)` in any controller, I want to always have a default. In my `User` model I'm doing this:

```rb
  after_commit :maybe_set_payment_processor

  def maybe_set_payment_processor
    if payment_processor.blank?
      set_payment_processor(:stripe)
    end
  end
```

I would love to be able to either set the default payment processor as part of the config, or as part of the user model.

Maybe something like:

```rb
Pay.setup do |config|
  # ... 
  config.default_payment_processor = :stripe
end
```

Or

```rb
class User < ApplicationRecord
  pay_customer default_payment_processor: :stripe
end
```

**Comment by excid3** [comment]
The second option might be good as we talked about adding other configuration options as well.

I think your `after_commit` would query the database every time the `User` model is saved? If we changed that to an `after_create_commit` we could have it run on creation easily, but that does not help if a record already exists.

Maybe we need to override the `payment_processor` method. Then anytime it is called, we can call `super` and see if there is a default payment processor already set and return that, otherwise create.

```ruby
has_one :payment_processor

def payment_processor
  current_processor = super

  # Create the default payment processor if needed
  if current_processor.blank? && self.class.default_payment_processor.present?
    set_payment_processor(self.class.default_payment_processor)
  end
end
```

Thoughts on that approach?

**Comment by cjavilla-stripe** [comment]
Oooh nice. I like your approach best. Lazily set the processor to the default if one exists only if `payment_processor` is run instead of every time the user is touched.
