### ISSUE TITLE
Support for Paddle Billing

### ISSUE THREAD

**Issue by deanpcmad** [pay-rails/pay#837]
Paddle have been working on improving their service for SaaS companies and have launched [Paddle Billing](https://www.paddle.com/billing). I've updated my Ruby library called [PaddleRB](https://github.com/deanpcmad/paddlerb) and would like to update Pay to take advantage of the new APIs.

Paddle Classic, which the previous service has been renamed to, will continue to function so existing code will need to be kept.

My proposal is for there to be an additional payment provider, maybe called `paddle_billing`, which would be for the new service. This would allow previous subscriptions, etc to still work fine and any new customers, subscriptions, transactions will be separate.

Would you be happy for me to do this? And if so, anything to consider? I'll likely clone the existing paddle code and update as required.

**Comment by excid3** [comment]
I saw on Twitter you beat me to the API updates. 👍 

I was talking with @cjilbert504 earlier and we were debating on renaming to `paddle_classic` and replacing `paddle` with Paddle Billing since all new Paddle customers will be using that and won't know about Classic at some point.

Regardless if we name the new processor `paddle` or `paddle_billing`, I still think the existing one should be renamed to `paddle_classic`.

This rename would be a major version bump, but it should only require that users:

1. Rename their credentials to `paddle_classic`
2. Update the Pay::Customer processor to `paddle_classic`

Unless I've forgotten something, that feels like a pretty simple migration to make.

I didn't look into how much the workflow has changed, but Paddle had a pretty simple integration which is good.

**Comment by deanpcmad** [comment]
Renaming the previous code to `paddle_classic` sounds good :+1: 

The API is very similar to Stripe where a Customer can have multiple Subscriptions, which is much better than it was before where a customer/subscription was the same thing

**Comment by excid3** [comment]
Oh good. I saw there was a Customer (that you can even create through the API now!). Seems like they've learned a lot, but sad they couldn't just fix their original code haha.

**Comment by courtsimas** [comment]
I noticed this got closed due to the premature merge. Is this good to go in master now or are changes still being made? I was about to dive into paddle billing (I'd rather not use classic at this point) and utilizing pay-rails would be awesome but I can't tell if the newest paddle processor solution/version is good to go?

**Comment by excid3** [comment]
Still working on it. Need to push up some more changes, but I think we're close. Just couldn't get it finished before I had to leave for Rails World 2023. Now that I'm back, we can hopefully get this shipped in a new version soon.

Keep an eye out for the next major version release which will be mainly for Paddle Billing.

**Comment by courtsimas** [comment]
Awesome news! Thanks!
